/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrental.client;

import javax.swing.JOptionPane;

/**
 * Login - Client Module
 * Provides user authentication interface for the Car Rental System.
 * Validates employee credentials against the server database.
 * Allows navigation to signup form for new users.
 *
 * @author Izaek Kisuule
 */
public class Login extends javax.swing.JFrame {



    /**
     * Creates new form Login.
     * Initializes the UI components, sets window properties, and centers the window.
     */
    
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Login Page");
        setSize(500, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblEmail = new javax.swing.JLabel();
        Lblpass = new javax.swing.JLabel();
        txtEmailField = new javax.swing.JTextField();
        Txtpass = new javax.swing.JPasswordField();
        Btnlogin = new javax.swing.JButton();
        BtnSignup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblEmail.setText("Email :");

        Lblpass.setText("Password : ");

        txtEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailFieldActionPerformed(evt);
            }
        });

        Btnlogin.setText("Login");
        Btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnloginActionPerformed(evt);
            }
        });

        BtnSignup.setText("Sign up ");
        BtnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignupActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("SIGN IN PLEASE || SIGN UP IF YOU HAVE NO ACCOUNT ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Lblpass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addComponent(LblEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(BtnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lblpass, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Txtpass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btnlogin)
                    .addComponent(BtnSignup))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles login button click event.
     * Validates email and password fields, sends authentication request to server,
     * and navigates to Dashboard on successful login.
     * 
     * @param evt the action event
     */
    private void BtnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnloginActionPerformed
       String email = txtEmailField.getText().trim();
        String password = String.valueOf(Txtpass.getPassword()).trim();
        
        if(email.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in the fields");
            return;
        }
        
        try {
            // We need to check if employee exists with this email and password
            // Since we don't have a direct login method, we'll list all employees and check manually
            String request = "LIST|Employees|";
            String response = ServerConnection.getInstance().sendRequest(request);
            
            String[] parts = response.split("\\|", 2);
            if (parts[0].equals("SUCCESS") && parts.length > 1) {
                String[] employees = parts[1].split(";");
                boolean found = false;
                
                // Check each employee by finding their details and comparing
                for (String employee : employees) {
                    int employeeId = Integer.parseInt(employee.split(" - ")[0]);
                    
                    // Get employee details to check email and password
                    String findRequest = "FIND|Employees|" + employeeId;
                    String findResponse = ServerConnection.getInstance().sendRequest(findRequest);
                    
                    String[] findParts = findResponse.split("\\|", 2);
                    if (findParts[0].equals("SUCCESS")) {
                        String[] fields = findParts[1].split(",");
                        String empEmail = fields[2]; // email is at index 2
                        String empPassword = fields[5]; // password_hash is at index 5
                        
                        if (empEmail.equals(email) && empPassword.equals(password)) {
                            found = true;
                            break;
                        }
                    }
                }
                
                if (found) {
                    JOptionPane.showMessageDialog(this, "You are logged in! Welcome");
                    new Dashboard().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid email or password!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error: " + 
                    (parts.length > 1 ? parts[1] : "Server error"));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Login Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_BtnloginActionPerformed

    /**
     * Handles signup button click event.
     * Opens the Signup form and closes the current login window.
     * 
     * @param evt the action event
     */
    private void BtnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignupActionPerformed
         
        new Signup().setVisible(true);
//        Signup.Main();
        this.dispose();
    }//GEN-LAST:event_BtnSignupActionPerformed

    /**
     * Handles email text field action event (e.g., Enter key press).
     * 
     * @param evt the action event
     */
    private void txtEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailFieldActionPerformed
        
    }//GEN-LAST:event_txtEmailFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSignup;
    private javax.swing.JButton Btnlogin;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel Lblpass;
    private javax.swing.JPasswordField Txtpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEmailField;
    // End of variables declaration//GEN-END:variables
}
